# This file can be used to customize the files managed by PDK.
#
# See https://github.com/danielparks/pdk-templates/blob/main/README.md
# for more information.
#
# See https://github.com/danielparks/pdk-templates/blob/main/config_defaults.yml
# for the default values.
---
spec/default_facts.yml:
  extra_facts:
    identity:
      gid: 0
      group: "wheel"
      privileged: true
      uid: 0
      user: "root"
